// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC7w9Z9vM51r98yOnTC3bMiA04YwdPWc8',
    appId: '1:632541947122:web:0134f152822724f2891c6b',
    messagingSenderId: '632541947122',
    projectId: 'grocery-918ec',
    authDomain: 'grocery-918ec.firebaseapp.com',
    storageBucket: 'grocery-918ec.appspot.com',
    measurementId: 'G-0XDRVW9EBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClf2zgoC8LUUwB0iVf_zBR_2r__y8uuLg',
    appId: '1:632541947122:android:c5f1e2eb178ce390891c6b',
    messagingSenderId: '632541947122',
    projectId: 'grocery-918ec',
    storageBucket: 'grocery-918ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpC2QcYcJqW6K8V0UYwK5LQdHlQ6EneM',
    appId: '1:632541947122:ios:75949b0fb61642d9891c6b',
    messagingSenderId: '632541947122',
    projectId: 'grocery-918ec',
    storageBucket: 'grocery-918ec.appspot.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWpC2QcYcJqW6K8V0UYwK5LQdHlQ6EneM',
    appId: '1:632541947122:ios:75949b0fb61642d9891c6b',
    messagingSenderId: '632541947122',
    projectId: 'grocery-918ec',
    storageBucket: 'grocery-918ec.appspot.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC7w9Z9vM51r98yOnTC3bMiA04YwdPWc8',
    appId: '1:632541947122:web:a60de713a8e4ec98891c6b',
    messagingSenderId: '632541947122',
    projectId: 'grocery-918ec',
    authDomain: 'grocery-918ec.firebaseapp.com',
    storageBucket: 'grocery-918ec.appspot.com',
    measurementId: 'G-6JEX235EZ8',
  );
}
